### ISSUE TITLE
Using a dynamic table for programming languages instead of a static text

### ISSUE THREAD

**Issue by Tintedfireglass** [AltF02/AltF02#1]
https://github-readme-stats.vercel.app/api/top-langs/?username=AltF02

You can modify this table to fit your readme's art style.
This will reduce a lot of work for you

**Comment by AltF02** [comment]
I don't do any work on this readme, its just a github action that runs every 24h. I appreciate it tho! If you're interested how, take a look at https://github.com/AltF02/AltF02/blob/master/.github/workflows/main.yml

**Comment by Tintedfireglass** [comment]
interesting...
thats a neat way to do it
